#!/usr/bin/env php
<?php

// unset time limit since the commands may take a while
set_time_limit(0);

require __DIR__ . '/vendor/autoload.php';


use GitS3\Console\Application;

$app = new Application('git-s3', '0.1.0');
$app->run();